server:
  port: 8081

spring:
  application:
    name: User
  datasource:
    url: jdbc:mysql://localhost:3306/user
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: Root
  jpa:
    hibernate:
      ddl-auto: update

    show-sql: true
eureka:
  instance:
    prefer-ip-address: true

  client:
    fetch-registry: true
    register-with-eureka: true
    

